# Generated by Django 2.2 on 2022-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
